---
# This Playbook would setup a local gemfire docker containers

- name: setup gemfire docker containers
  hosts: localhost
  roles:
    - docker
    - docker_provision_gemfire_network
    - docker_provision_gemfire_containers
  environment:
    DOCKER_HOST: tcp://192.168.99.50:2376
    DOCKER_CERT_PATH: "{{ lookup('env', 'HOME') }}/.docker/machine/machines/gemfire"
    DOCKER_TLS_VERIFY: 1


- name: finalize gemfire docker containers
  hosts: gf_cluster
  roles:
    - docker_finalize_gemfire_container
    - williamyeh.oracle-java
  vars:
    java_download_from_oracle: false
    java_remove_download: false
    java_version: 8
    java_subversion: 121
    java_build: 13
    java_set_javahome: true
  become: true
  become_method: sudo
