---
# This Playbook would setup a local gemfire docker containers

- name: setup docker and gemfire docker machine
  hosts: localhost
  roles:
    - docker


- name: setup gemfire docker network and containers
  hosts: localhost
  pre_tasks:
    - name: register gemfire_docker_machine_ip_echo
      shell: echo $(docker-machine ip gemfire)
      register: gemfire_docker_machine_ip_echo
    - name: set facts for docker containers
      set_fact:
        docker_host: "tcp://{{ gemfire_docker_machine_ip_echo.stdout }}:2376"
        tls_verify: 1
        cacert_path: "{{ lookup('env', 'HOME') }}/.docker/machine/machines/gemfire/ca.pem"
        cert_path: "{{ lookup('env', 'HOME') }}/.docker/machine/machines/gemfire/cert.pem"
        key_path: "{{ lookup('env', 'HOME') }}/.docker/machine/machines/gemfire/key.pem"
  roles:
    - docker_provision_gemfire_network
    - docker_provision_gemfire_containers


- name: finalize gemfire docker containers
  hosts: gf_cluster
  roles:
    - docker_finalize_gemfire_container
    - williamyeh.oracle-java
  vars:
    java_download_from_oracle: false
    java_remove_download: false
    java_version: 8
    java_subversion: 121
    java_build: 13
    java_set_javahome: true
  become: true
  become_method: sudo
