#!/usr/bin/env bash
#
# Sets up requirements to provision with ansible
#

#
# Clean display function
#
# usage:
#        display "My thing to output"
#
function display() {
    echo "----> $1"
}

if [ ! `which pip` ]
then
    display "Installing pip"
    sudo easy_install pip
fi

sudo -H pip install --force-reinstall --ignore-installed --upgrade -r requirements.txt
sudo ansible-galaxy remove williamyeh.oracle-java
sudo ansible-galaxy install williamyeh.oracle-java
sudo chown -R ${USER:=$(/usr/bin/id -run)}:${GROUP:=$(/usr/bin/id -g -n $USER)} ~/.ansible*

if [ ! `which brew` ]
then
    display "Installing Homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
